packages:
  - example
  - example/playground

overrides:
  "@nuxt/kit": "~4.4.8"
  "@nuxt/module-builder": "workspace:*"
  "@nuxt/schema": "~4.4.8"
  nuxt: "~4.4.8"
  typescript: "~5.9.3"
  vue: "^3.5.39"
  vue-tsc: "^3.3.7"

shellEmulator: true

allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  unrs-resolver: false
