name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: corepack enable
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - run: pnpm dev:prepare

      - name: 🔠 Lint project
        run: pnpm lint

      - name: ✂️ Knip project
        run: pnpm test:knip

      - name: ⚙️ Check package engines
        run: pnpm test:engines

      - name: 💪 Check published types
        run: pnpm test:attw

      - name: 📦 Check `package.json`
        run: pnpm test:publint

  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: corepack enable
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/-1
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - run: pnpm dev:prepare

      - name: 🧪 Test project
        run: pnpm test

      - name: 🛠 Build project
        run: pnpm build

      - name: 🛠 Build project (example)
        run: pnpm example:build

      - name: 💪 Type check
        run: pnpm test:types
